/* eslint-disable camelcase */
const okay_with = 'okay_with';
const played_with = 'played_with';
const comfortable = 'comfortable';

const librariesUsed = {
  Javascript: {
    name: 'Javascript',
    logo: 'images/libraries/transparent/187_Js_logo_logos-512.png',
    comfortLevel: comfortable,
    transparent: true,
    key: 1,
  },
  Git: {
    name: 'Git',
    logo: 'images/libraries/transparent/1280px-Git-logo.svg.png',
    comfortLevel: comfortable,
    transparent: true,
    key: 2,
  },
  Node: {
    name: 'Node',
    logo: 'images/libraries/transparent/1280px-Node.js_logo.svg.png',
    comfortLevel: comfortable,
    transparent: true,
    key: 3,
  },
  CSS: {
    name: 'CSS',
    logo: 'images/libraries/transparent/css-logo.png',
    comfortLevel: okay_with,
    transparent: true,
    key: 4,
  },
  Express: {
    name: 'Express',
    logo: 'images/libraries/transparent/express-facebook-share.png',
    comfortLevel: comfortable,
    transparent: false,
    key: 5,
  },
  Redux: {
    name: 'Redux',
    logo: 'images/libraries/transparent/logo-redux.png',
    comfortLevel: comfortable,
    transparent: true,
    key: 6,
  },
  'Travis CI': {
    name: 'Travis CI',
    logo: 'images/libraries/transparent/travis-ci-logo.png',
    comfortLevel: okay_with,
    transparent: true,
    key: 7,
  },
  Three: {
    name: 'Three',
    logo: 'images/libraries/transparent/three-js-logo.png',
    comfortLevel: played_with,
    transparent: true,
    key: 8,
  },
  'React-redux': {
    name: 'React-redux',
    logo: 'images/libraries/transparent/react-redux-symbols.png',
    comfortLevel: comfortable,
    transparent: true,
    key: 9,
  },
  Phaser: {
    name: 'Phaser',
    logo: 'images/libraries/transparent/phaser3-square-logo.png',
    comfortLevel: played_with,
    transparent: true,
    key: 10,
  },
  'mocha-chai': {
    name: 'mocha-chai',
    logo: 'images/libraries/transparent/mocha-chai.png',
    comfortLevel: okay_with,
    transparent: true,
    key: 11,
  },
  Socket: {
    name: 'Socket',
    logo: 'images/libraries/white/socket-io-logo.png',
    comfortLevel: okay_with,
    transparent: false,
    key: 12,
  },
  php: {
    name: 'php',
    logo: 'images/libraries/white/php-logoTransparent.png',
    comfortLevel: played_with,
    transparent: false,
    key: 13,
  },
  Sequelize: {
    name: 'Sequelize',
    logo: 'images/libraries/white/sequelize-white-background-logo.png',
    comfortLevel: comfortable,
    transparent: false,
    key: 14,
  },
  Mocha: {
    name: 'Mocha',
    logo: 'images/libraries/white/mocha-long-logo2.png',
    comfortLevel: okay_with,
    transparent: false,
    key: 15,
  },

  React: {
    name: 'React',
    logo: 'images/libraries/transparent/react-logo.png',
    comfortLevel: comfortable,
    transparent: true,
    key: 16,
  },
  'React-Hooks': {
    name: 'React-Hooks',
    logo: 'images/libraries/white/ReactHooksWhiteBackground.png',
    comfortLevel: comfortable,
    transparent: false,
    key: 17,
  },
  HTML: {
    name: 'html',
    logo: 'images/libraries/transparent/html5-logo-31819.png',
    comfortLevel: comfortable,
    transparent: true,
    key: 18,
  },

  Postgres: {
    name: 'PostgreSQL',
    logo: 'images/libraries/postgresql-logo.png',
    comfortLevel: comfortable,
    transparent: false,
    key: 17,
  },
  heroku: {
    name: 'heroku',
    logo: 'images/libraries/Heroku_logo.png',
    comfortLevel: okay_with,
    transparent: false,
    key: 19,
  },
  SQL: {
    name: 'SQL',
    logo: 'images/libraries/sqlLogo.jpeg',
    comfortLevel: okay_with,
    transparent: false,
    key: 20,
  },

  Bootstrap: {
    name: 'Bootstrap',
    logo: 'images/libraries/Bootstrap-Logo.png',
    comfortLevel: played_with,
    transparent: false,
    key: 21,
  },
  WebRTC: {
    name: 'WebRTC',
    logo: 'images/libraries/Webrtc.png',
    comfortLevel: played_with,
    transparent: false,
    key: 22,
  },
  'Digital Ocean': {
    name: 'Digital Ocean',
    logo: 'images/libraries/1200px-DigitalOcean_logo.png',
    comfortLevel: played_with,
    transparent: false,
    key: 23,
  },
  StepZen: {
    name: 'StepZen',
    logo: 'images/libraries/StepZen.png',
    comfortLevel: played_with,
    transparent: false,
    key: 24,
  },
  GraphQL: {
    name: 'GraphQL',
    logo: 'images/libraries/GraphQL.png',
    comfortLevel: played_with,
    transparent: false,
    key: 25,
  },
  'Material-ui': {
    name: 'Material-ui',
    logo: 'images/libraries/material-ui-Logo.png',
    comfortLevel: played_with,
    transparent: false,
    key: 26,
  },
  Next: {
    name: 'Next.js',
    logo: 'images/libraries/nextjs.jpeg',
    comfortLevel: played_with,
    transparent: false,
    key: 27,
  },
  // {name: "Git", logo: "", comfortLevel: played_with, transparent: false, key: 28},
  // {name: "Git", logo: "", comfortLevel: played_with, transparent: false, key: 29},
  // {name: "Git", logo: "", comfortLevel: played_with, transparent: false, key: 30},
};

export default librariesUsed;
