const workHistory = [
  {
    key: 5,
    companyLogo: 'images/fullstack-academy-logo-color-on-white.png',
    companyName: 'Fullstack Academy',
    JobTitle: 'Software Engineering/Web Development Instructional Associate',
    start: 'July 2021',
    end: 'December 2021',
    description: [
      'Teaching assistant to a cohort of 12 junior web developers covering: software engineering concepts, computer science fundamentals, debugging techniques, schema design, pair programming',
      'Librarys and frameworks taught were: jquery, Javascript, React, Node, Express, CSS and HTML',
      'Conducted mock technical interviews and impromptu lectures',
      'Ran weekly Office Hours',
    ],
  },
  {
    key: 3,
    companyLogo: 'images/LittleLogoTransparent.png',
    companyName: 'Wheaton Community Radio Amateurs',
    JobTitle: 'Webmaster',
    start: 'November 2019',
    end: 'Present',
    link: 'w9ccu.org',
    description: [
      'Integrate PayPal allowing membership dues, Hamfest tickets and vendor orders to be processed and paid online',
      'Update website monthly with meeting minutes and notices for club membership',
      'Enhanced online renewals form using Javascript, PHP, HTML and CSS allowing for emails are sent upon submission.',
      'rebuild and redesigned website with Wordpress',
    ],
  },
  {
    key: 4,
    companyLogo: 'images/fullstack-academy-logo-color-on-white.png',
    companyName: 'Fullstack Academy',
    JobTitle: 'Software Engineering/Web Development Teaching Fellow',
    start: 'November 2020',
    end: 'February 2021',
    description: [
      'Teaching assistant to a cohort of 40+ students covering: software engineering concepts, computer science fundamentals, debugging techniques, schema design and pair programming',
      'Acted as project manager and technical mentor for teams of 4 students during 4 projects, employing the use of agile methodologies',
      'Conducted technical admissions interviews',
      'Ran weekly whiteboarding lectures',
    ],
  },
  {
    key: 1,
    companyLogo: 'images/LittleLogoTransparent.png',
    companyName: 'Wheaton Community Radio Amateurs',
    JobTitle: 'Hamfest Chairman',
    start: 'February 2016',
    end: 'January 2020',
    description: [
      'Organized a radio, computer and electronics expo with over 750 attendees',
      'Handled communication with vendors and six subcommittees',
      'Brought in $2000 each year for the club',
    ],
  },
  {
    key: 2,
    companyLogo: 'images/209-2092285_office-depot-office-max-png-logo.png',
    companyName: 'Office Depot',
    JobTitle: 'Print and Copy Supervisor',
    start: 'April 2015',
    end: 'February 2020',
    description: [
      'Trained co-workers on new equipment and procedures',
      'Ensured supplies were in-stock to produce client orders',
      'Handled placing and producing orders for over 50 clients a week',
      'Achieved over department sales goals almost every quarter',
    ],
  },
];
export default workHistory
